server:
  port: 8088

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

spring:
  application:
      name: eureka_client_a
  datasource:
    continue-on-error: true
    initialization-mode: always
    url: jdbc:postgresql://localhost:5432/admindb
    username: admindb
    password: admindb
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

