version: '2.1'
services:
  db:
    image: postgres:latest
    container_name: admin_db
    environment: 
      - POSTGRES_DB=admindb
      - POSTGRES_USER=admindb
      - POSTGRES_PASSWORD=admindb
    ports:
      - "5440:5432"
    healthcheck:
      test: "exit 0"
      
  eureka:
    image: 06795/telekom_micro_eureka
    container_name: telekom_micro_eureka
    ports:
      - "8761:8761"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: "exit 0"
  
  eureka_client_admin:
    image: 06795/telekom_micro_eureka_client_admin
    container_name: telekom_micro_eureka_client_admin
    depends_on:
      eureka:
        condition: service_healthy
    ports:
      - "8092:8092"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/admindb
      SPRING_DATASOURCE_USERNAME: admindb
      SPRING_DATASOURCE_PASSWORD: admindb
      
  eureka_client_a:
    image: 06795/telekom_micro_eureka_client_a
    container_name: telekom_micro_eureka_client_a
    depends_on:
      eureka:
        condition: service_healthy
    ports:
      - "8088:8088"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/admindb
      SPRING_DATASOURCE_USERNAME: admindb
      SPRING_DATASOURCE_PASSWORD: admindb
      
  eureka_client_b:
    image: 06795/telekom_micro_eureka_client_b
    container_name: telekom_micro_eureka_client_b
    depends_on:
      eureka:
        condition: service_healthy
    ports:
      - "8089:8089"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/admindb
      SPRING_DATASOURCE_USERNAME: admindb
      SPRING_DATASOURCE_PASSWORD: admindb
      
  eureka_zuul_gateway:
    image: 06795/telekom_micro_eureka_zuul_gateway
    container_name: telekom_micro_eureka_zuul_gateway
    depends_on:
      eureka:
        condition: service_healthy
    ports:
      - "8090:8090"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/admindb
      SPRING_DATASOURCE_USERNAME: admindb
      SPRING_DATASOURCE_PASSWORD: admindb
      
  eureka_client_file:
    image: 06795/telekom_micro_eureka_client_file
    container_name: telekom_micro_eureka_client_file
    depends_on:
      eureka:
        condition: service_healthy
    ports:
      - "8091:8091"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/admindb
      SPRING_DATASOURCE_USERNAME: admindb
      SPRING_DATASOURCE_PASSWORD: admindb
