server:
  port: 8090

spring:
  cloud:
    refresh:
      enabled: false
  application:
      name: eureka_zuul
  datasource:
    continue-on-error: true
    initialization-mode: always
    url: jdbc:postgresql://localhost:5432/admindb
    username: admindb
    password: admindb
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

zuul:
  routes:
    eureka_client_b:
      path:
        /service/B/**
      service_id:
        eureka_client_b
      strip-prefix:
        false
      sensitive-headers:
    eureka_client_a:
          path:
            /service/A/**
          service_id:
            eureka_client_a
          strip-prefix:
            false
          sensitive-headers:
    eureka_client_admin:
              path:
                /admin/tool/**
              service_id:
                eureka_client_admin
              strip-prefix:
                false
              sensitive-headers:
    eureka_client_file:
              path:
                /file/**
              service_id:
                eureka_client_file
              strip-prefix:
                false
              sensitive-headers:
